# =========================
#  Chirpy project-site config
#  https://krishna-zbxc.github.io/thing
# =========================

# --- Theme & locale ---
theme: jekyll-theme-chirpy
lang: en
timezone: Europe/Helsinki

# --- Identity & SEO ---
title: "Theme blog thing"           # ← change to your site name
tagline: "the tagline ahahhahah"    # ← update whenever
description: >-
  somee description                  # ← 1–2 sentence summary for SEO/social cards

# --- URL setup (project site on GitHub Pages) ---
url: "https://krishna-zbxc.github.io"  # no trailing slash
baseurl: "/thing"                      # MUST start with slash for project sites

# --- Author / Social ---
github:
  username: krishna-zbxc

social:
  name: "Krishna"                      # display name in footer
  email: "email@example.com"           # replace
  links:
    - https://github.com/krishna-zbxc  # first link becomes footer copyright link

# --- Appearance / Media ---
avatar:                                 # e.g., /assets/img/avatar.png
social_preview_image:                   # e.g., /assets/img/og-default.png
toc: true

# --- Analytics (optional) ---
analytics:
  google:
    id:                                 # e.g., G-XXXXXXXXXX

# --- Comments (pick ONE provider; example shows Giscus) ---
comments:
  provider: giscus
  giscus:
    repo: ""                            # e.g., krishna-zbxc/thing
    repo_id: ""                         # from giscus.app setup
    category: ""                        # e.g., General
    category_id: ""                     # from giscus.app setup
    mapping: pathname
    strict: 0
    input_position: bottom
    lang: en
    reactions_enabled: 1
# Tip: enable Discussions + install Giscus app on the repo before filling IDs. :contentReference[oaicite:1]{index=1}

# --- PWA (service worker relies on correct baseurl) ---
pwa:
  enabled: true
  cache:
    enabled: true
  deny_paths:                           # add patterns to exclude, if needed

# --- Content & build ---
paginate: 10

kramdown:
  footnote_backlink: "↩︎"

syntax_highlighter: rouge
syntax_highlighter_opts:
  css_class: highlight
  block:
    line_numbers: true
    start_line: 1
  span:
    line_numbers: false

# --- Collections / Defaults used by Chirpy ---
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: "/:title/"

# --- Permalinks ---
permalink: /posts/:title/

# --- SASS / HTML compression ---
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# --- Excludes to keep the build clean ---
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# --- Archives (tags & categories pages) ---
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
